apiVersion: apps/v1
kind: Deployment
metadata:
  name: barak-web
  labels:
    app: barak-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barak-web
  template:
    metadata:
      labels:
        app: barak-web
    spec:
      containers:
      - name: barak-web
        image: doleval013/barak-web:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: barak-web-service
spec:
  selector:
    app: barak-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  # On k3s/Single-Node, 'ClusterIP' is usually enough if using Ingress, 
  # but LoadBalancer is fine too (ServiceLB). 
  # For Traefik to pick it up easily, let's keep it simple.
  type: ClusterIP 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: barak-web-ingress
  annotations:
    # Tell Traefik to handle this simple catch-all rule
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: dogs.barakaloni.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: barak-web-service
            port:
              number: 80
