apiVersion: apps/v1
kind: Deployment
metadata:
  name: barak-web
  labels:
    app: barak-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barak-web
  template:
    metadata:
      labels:
        app: barak-web
    spec:
      containers:
      - name: barak-web
        image: doleval013/barak-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: barak-web-service
spec:
  selector:
    app: barak-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # On k3s/Single-Node, 'ClusterIP' is usually enough if using Ingress, 
  # but since Traefik is missing/disabled, we use LoadBalancer to expose port 80 directly.
  # Switch back to internal ClusterIP because the Ingress Controller will be the LoadBalancer now
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: barak-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Force HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - dogs.barakaloni.com
    secretName: barak-web-tls
  rules:
  - host: dogs.barakaloni.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: barak-web-service
            port:
              number: 80
